/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_matthewacon_pal_agent_bootstrap_PalClassLoader */

#ifndef _Included_io_github_matthewacon_pal_agent_bootstrap_PalClassLoader
#define _Included_io_github_matthewacon_pal_agent_bootstrap_PalClassLoader
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
