/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_matthewacon_pal_api_bytecode_PalProcessor */

#ifndef _Included_io_github_matthewacon_pal_api_bytecode_PalProcessor
#define _Included_io_github_matthewacon_pal_api_bytecode_PalProcessor
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
