/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_matthewacon_pal_DisposableClassLoader */

#ifndef _Included_io_github_matthewacon_pal_DisposableClassLoader
#define _Included_io_github_matthewacon_pal_DisposableClassLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_matthewacon_pal_DisposableClassLoader
 * Method:    redefineClass
 * Signature: ([B)Ljava/lang/Class;
 */
JNIEXPORT jclass JNICALL Java_io_github_matthewacon_pal_DisposableClassLoader_redefineClass
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
