/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_matthewacon_pal_ExceptionUtils_ReflectionHandler */

#ifndef _Included_io_github_matthewacon_pal_ExceptionUtils_ReflectionHandler
#define _Included_io_github_matthewacon_pal_ExceptionUtils_ReflectionHandler
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
