/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_matthewacon_pal_util_NativeUtils */

#ifndef _Included_io_github_matthewacon_pal_util_NativeUtils
#define _Included_io_github_matthewacon_pal_util_NativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_matthewacon_pal_util_NativeUtils
 * Method:    getInstanceFromStack
 * Signature: (I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_io_github_matthewacon_pal_util_NativeUtils_getInstanceFromStack
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
