/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_matthewacon_pal_api_annotations_sourcecode_Literal_LiteralProcessor */

#ifndef _Included_io_github_matthewacon_pal_api_annotations_sourcecode_Literal_LiteralProcessor
#define _Included_io_github_matthewacon_pal_api_annotations_sourcecode_Literal_LiteralProcessor
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
