/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_matthewacon_pal_javax_processors_PalBootstrapAnnotationProcessor */

#ifndef _Included_io_github_matthewacon_pal_javax_processors_PalBootstrapAnnotationProcessor
#define _Included_io_github_matthewacon_pal_javax_processors_PalBootstrapAnnotationProcessor
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
