/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_matthewacon_pal_util_IOUtils */

#ifndef _Included_io_github_matthewacon_pal_util_IOUtils
#define _Included_io_github_matthewacon_pal_util_IOUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_matthewacon_pal_util_IOUtils
 * Method:    getBlockSize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_github_matthewacon_pal_util_IOUtils_getBlockSize
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
