/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_matthewacon_pal_PalAgent_JavaCompilerInterceptors_Close */

#ifndef _Included_io_github_matthewacon_pal_PalAgent_JavaCompilerInterceptors_Close
#define _Included_io_github_matthewacon_pal_PalAgent_JavaCompilerInterceptors_Close
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
