/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_matthewacon_pal_util_LambdaUtils_RCase_CaseFunction */

#ifndef _Included_io_github_matthewacon_pal_util_LambdaUtils_RCase_CaseFunction
#define _Included_io_github_matthewacon_pal_util_LambdaUtils_RCase_CaseFunction
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
