/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_matthewacon_pal_util_RuntimeAnnotationGenerator_GeneratorContext */

#ifndef _Included_io_github_matthewacon_pal_util_RuntimeAnnotationGenerator_GeneratorContext
#define _Included_io_github_matthewacon_pal_util_RuntimeAnnotationGenerator_GeneratorContext
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
