/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_matthewacon_pal_agent_AbstractLogInterceptors */

#ifndef _Included_io_github_matthewacon_pal_agent_AbstractLogInterceptors
#define _Included_io_github_matthewacon_pal_agent_AbstractLogInterceptors
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
