/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_matthewacon_pal_PalAgent_JavaCompilerInterceptors_Construct */

#ifndef _Included_io_github_matthewacon_pal_PalAgent_JavaCompilerInterceptors_Construct
#define _Included_io_github_matthewacon_pal_PalAgent_JavaCompilerInterceptors_Construct
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
