/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_matthewacon_pal_PalAgent */

#ifndef _Included_io_github_matthewacon_pal_PalAgent
#define _Included_io_github_matthewacon_pal_PalAgent
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
